using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace GameScan
{
    /// <summary>
    /// Emits the compact baseline the MOD carries, so it can tell at boot whether the game it is
    /// running against is the one it was built for.
    ///
    /// Deliberately much weaker than the offline diff, because the runtime has different limits:
    ///
    ///   * IL bodies cannot be hashed at load without paying a real startup cost, so behaviour
    ///     changes are NOT detectable here. Only the offline scan sees those.
    ///   * Cecil's type names and reflection's type names disagree on generics
    ///     (`Dictionary`2&lt;K,V&gt;` vs `Dictionary`2[[...]]`), so comparing signature hashes
    ///     across the two would fire constantly on things that never changed.
    ///
    /// What survives both constraints is existence and arity — which is exactly what catches the
    /// renames, removals and parameter changes that make Harmony throw. Everything else is left
    /// to tools/gamescan.ps1, and the log says so rather than implying a stronger guarantee.
    /// </summary>
    public static class GuardBuilder
    {
        public static string Build(Manifest manifest, Contract contract)
        {
            // Collapse the contract to the distinct (type, member name, arity) triples worth
            // checking. Field and property arity is meaningless, so it is recorded as -1.
            var entries = new SortedSet<string>(StringComparer.Ordinal);
            var types = new SortedSet<string>(StringComparer.Ordinal);

            foreach (var key in contract.Uses.Keys)
            {
                var sep = key.IndexOf("::", StringComparison.Ordinal);
                if (sep < 0)
                {
                    if (manifest.Types.ContainsKey(key)) types.Add(key);
                    continue;
                }

                var typeName = key.Substring(0, sep);
                if (!manifest.Types.TryGetValue(typeName, out var type)) continue;
                types.Add(typeName);

                var memberPart = key.Substring(sep + 2);
                var wanted = memberPart.StartsWith("#", StringComparison.Ordinal)
                    ? memberPart.Substring(1)
                    : Differ.MemberName(memberPart);

                foreach (var (mk, entry) in type.Members)
                {
                    if (Differ.MemberName(mk) != wanted) continue;
                    var arity = entry.Kind == "method" ? Arity(mk) : -1;
                    entries.Add($"{typeName}|{wanted}|{arity}");
                }
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//   Generated by tools/gamescan (`tools\\gamescan.ps1 -Guard`). DO NOT EDIT.");
            sb.AppendLine("//");
            sb.AppendLine("//   The subset of the game's API this mod depends on, as of the baseline build.");
            sb.AppendLine("//   GameGuard checks it at boot so that a silent Steam update to the base game");
            sb.AppendLine("//   shows up as a named warning instead of an unexplained crash.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("namespace PunkMultiverse.Core");
            sb.AppendLine("{");
            sb.AppendLine("    internal static class GameBaseline");
            sb.AppendLine("    {");
            sb.AppendLine($"        /// <summary>Game build the baseline was captured from.</summary>");
            sb.AppendLine($"        public const string GameVersion = \"{manifest.Assembly.GameVersion}\";");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>Module version id of Punk.Main.dll. Differs on ANY recompile of the");
            sb.AppendLine("        /// game, so it is the cheap first question: did the assembly change at all?</summary>");
            sb.AppendLine($"        public const string Mvid = \"{manifest.Assembly.Mvid}\";");
            sb.AppendLine();
            sb.AppendLine($"        /// <summary>Types the mod references ({types.Count}).</summary>");
            sb.AppendLine("        public static readonly string[] Types =");
            sb.AppendLine("        {");
            foreach (var t in types) sb.AppendLine($"            \"{t}\",");
            sb.AppendLine("        };");
            sb.AppendLine();
            sb.AppendLine($"        /// <summary>\"Type|Member|Arity\" the mod depends on ({entries.Count}).");
            sb.AppendLine("        /// Arity -1 means a field or property, where it does not apply.</summary>");
            sb.AppendLine("        public static readonly string[] Members =");
            sb.AppendLine("        {");
            foreach (var e in entries) sb.AppendLine($"            \"{e}\",");
            sb.AppendLine("        };");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        static int Arity(string memberKey)
        {
            var open = memberKey.IndexOf('(');
            var close = memberKey.LastIndexOf(')');
            if (open < 0 || close <= open) return -1;
            var inner = memberKey.Substring(open + 1, close - open - 1);
            if (inner.Length == 0) return 0;

            // Parameter types can themselves contain commas inside generic arguments, so count
            // only the separators at depth zero.
            var depth = 0;
            var count = 1;
            foreach (var ch in inner)
            {
                if (ch == '<' || ch == '[') depth++;
                else if (ch == '>' || ch == ']') depth--;
                else if (ch == ',' && depth == 0) count++;
            }
            return count;
        }
    }
}
